### ISSUE TITLE
example nodes won't show up

### ISSUE THREAD

**Issue by kmligue** [n8n-io/n8n-nodes-starter#42]
i followed all the installation steps but the example nodes won't show up.

**Comment by Joffcom** [comment]
Hey @kmligue 

Can you share the commands you ran and your project? A node can fail to appear if there is a code issue or if the npm link commands were not ran in the correct locations.

**Comment by kmligue** [comment]
@Joffcom https://www.loom.com/share/55fc70855c8b4b62bbcf58410f1fcf58

**Comment by adrianPrestamo** [comment]
Hello! I am experiencing the exact same problem.
I am following this tutorial (official)
[Tutorial](https://youtu.be/OI6zHJ56eW0)
And I experience the same error output but when runing npm install in the n8n-nodes-webinar (I have a diferent name)
However, I can "bypass" the warning runing it with --legacy-peer-deps.
Anyways, when doing that, if i then run the link commands (in the webinar dir and in the n8n package folder)
I get no error but the nodes won't show up.
If I dont run it with the --legacy flag I experience the same error.

I made a post [here](https://community.n8n.io/t/installation-errors-when-setting-up-for-custom-node-developement/31746)

**Comment by Joffcom** [comment]
Hey @kmligue & @adrianPrestamo,

The path you are running the `npm link n8n-nodes-x` command in is not correct. It would be something like `~/.n8n/nodes` which would be one of the 3 paths below depending on the OS.

**Windows:** C:/Users/username/.n8n/nodes
**MacOS:** /Users/username/.n8n/nodes
**Linux:** /home/username/.n8n/nodes

I will get the documentation updated to make this clearer.

**Comment by adrianPrestamo** [comment]
@Joffcom Okey! Thanks.
Anyways the problem is the you tube tutorial [here](https://youtu.be/OI6zHJ56eW0)
I have tried your what you said as @maspio said in the forum post I created.
It still doesn't show up or displays this error:

```
npm WARN node_modules/n8n/node_modules/n8n-nodes-base
npm WARN   n8n-nodes-base@"1.9.3" from n8n@1.9.3
npm WARN   node_modules/n8n
npm WARN     n8n@"^1.9.0" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer n8n-nodes-base@"1.9.2" from n8n-core@1.9.1
npm WARN node_modules/n8n/node_modules/n8n-core
npm WARN   n8n-core@"1.9.1" from n8n@1.9.3
npm WARN   node_modules/n8n
npm WARN
npm WARN Conflicting peer dependency: n8n-nodes-base@1.9.2
npm WARN node_modules/n8n-nodes-base
npm WARN   peer n8n-nodes-base@"1.9.2" from n8n-core@1.9.1
npm WARN   node_modules/n8n/node_modules/n8n-core
npm WARN     n8n-core@"1.9.1" from n8n@1.9.3
npm WARN     node_modules/n8n
```

This are warnings when installing n8n with npm but they become Errors when linking

**Comment by Joffcom** [comment]
Hey @kmligue,

I am not seeing the errors when running this project but looking at that output are you using the code here as it is or are you trying to make your own node that uses the AWS SDK?

**Comment by sgoncharov1** [comment]
@Joffcom I had the exact same problem on Mac, and your comment about doing link to custom nodes from another location solved it. Thanks a lot !
 
MacOS: /Users/username/.n8n/custom

**Comment by adrianPrestamo** [comment]
Hey @Joffcom,

I am only using the n8n-nodes-starter (this repo) that you have published. I was just trying to get the basic ones to show in the n8n editor.

I have reinstalled n8n, reinstalled the starter package , went to .n8n and created the custom folder. ran npm init and npm install. then after n8n start i get:

the sequence:

npm install n8n -g
(move to repo folder)
npm install
npm link
(move to .n8n folder)
mkdir custom
cd custom
npm init
npm install
n8n start

all the sequence runs without errors except for the n8n start.

PS C:\Users\aprestamo> n8n start
Initializing n8n process
Error loading node "isomorphic" from: "C:/Users/aprestamo/.n8n/custom/node_modules/n8n-my-nodes/node_modules/@jsdevtools/ono/cjs/isomorphic.node.js" - require(...).isomorphic is not a constructor
evalmachine.<anonymous>:1
new (require('C:/Users/aprestamo/.n8n/custom/node_modules/n8n-my-nodes/node_modules/@jsdevtools/ono/cjs/isomorphic.node.js').isomorphic)()
^

TypeError: require(...).isomorphic is not a constructor
    at evalmachine.<anonymous>:1:1
    at Script.runInContext (node:vm:135:12)
    at loadClassInIsolation (C:\Users\aprestamo\AppData\Roaming\npm\node_modules\n8n\node_modules\n8n-core\src\ClassLoader.ts:9:16)
    at CustomDirectoryLoader.loadNodeFromFile (C:\Users\aprestamo\AppData\Roaming\npm\node_modules\n8n\node_modules\n8n-core\src\DirectoryLoader.ts:75:35)
    at CustomDirectoryLoader.loadAll (C:\Users\aprestamo\AppData\Roaming\npm\node_modules\n8n\node_modules\n8n-core\src\DirectoryLoader.ts:288:10)
    at LoadNodesAndCredentials.runDirectoryLoader (C:\Users\aprestamo\AppData\Roaming\npm\node_modules\n8n\src\LoadNodesAndCredentials.ts:248:3)
    at LoadNodesAndCredentials.loadNodesFromCustomDirectories (C:\Users\aprestamo\AppData\Roaming\npm\node_modules\n8n\src\LoadNodesAndCredentials.ts:170:4)
    at LoadNodesAndCredentials.init (C:\Users\aprestamo\AppData\Roaming\npm\node_modules\n8n\src\LoadNodesAndCredentials.ts:89:3)
    at Start.init (C:\Users\aprestamo\AppData\Roaming\npm\node_modules\n8n\src\commands\BaseCommand.ts:53:3)
    at Start.init (C:\Users\aprestamo\AppData\Roaming\npm\node_modules\n8n\src\commands\start.ts:213:3)
Error: Exiting due to an error.
TypeError: require(...).isomorphic is not a constructor

**Comment by adrianPrestamo** [comment]
Hello @Joffcom 
i have tried your steps and it worked. 
thank you very much!

**Comment by kmligue** [comment]
https://www.loom.com/share/1763ab6f100844e6a8c7161ba58e1a50
@Joffcom can you please check video above. i already run the commands prior to that.

**Comment by muhammed671** [comment]
> Hey @adrianPrestamo,
> 
> The steps should be...
> 
> ```
> npm install n8n -g
> (move to repo folder)
> npm install
> npm link
> (move to .n8n folder)
> mkdir custom
> cd custom
> npm init
> npm link n8n-nodes-your-node-name
> n8n start
> ```
> 
> Can you try that and see if changes anything, You might need to clear your custom folder as well.

Hi, it dowsnt work any more for me on my macos

**Comment by Rakeh-vallangi** [comment]
@muhammed671  did u figure it out?

**Comment by Rakeh-vallangi** [comment]
@Joffcom it doesn't work on macos
